# Generated by Django 4.2.6 on 2024-03-25 12:30

import re

import account.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("IST", "Identity Staking")],
                        db_index=True,
                        max_length=3,
                    ),
                ),
                ("active", models.BooleanField(default=False)),
                ("content", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="TosAcceptanceProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("address", account.models.EthAddressField(max_length=42)),
                (
                    "signature",
                    account.models.EthSignature(
                        max_length=132,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^0x[A-Fa-f0-9]+$"),
                                "Enter a valid hex string ",
                                "invalid",
                            ),
                            django.core.validators.RegexValidator(
                                re.compile("^0x[A-Fa-f0-9]+$"),
                                "Enter a valid hex string ",
                                "invalid",
                            ),
                        ],
                    ),
                ),
                ("nonce", account.models.NonceField(max_length=60, unique=True)),
                (
                    "tos",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="acceptance_proofs",
                        to="tos.tos",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="tos",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("type", "active"),
                name="unique_active_tops_for_type",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tosacceptanceproof",
            unique_together={("tos", "address")},
        ),
    ]
