# Generated by Django 4.2.6 on 2024-03-26 16:52

import re

import django.core.validators
from django.db import migrations, models

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ("tos", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="tos",
            name="unique_active_tops_for_type",
        ),
        migrations.AddField(
            model_name="tos",
            name="final",
            field=models.BooleanField(
                default=False,
                help_text="Once an object is made final, it cannot be edited any more. This is to prevent from editing TOS that might have been accepted by users.",
            ),
        ),
        migrations.AlterField(
            model_name="tos",
            name="active",
            field=models.BooleanField(
                default=False,
                help_text="Only 1 active tos is alloed per type. The active is the one that will be required for users to approve",
            ),
        ),
        migrations.AlterField(
            model_name="tosacceptanceproof",
            name="signature",
            field=account.models.EthSignature(
                max_length=132,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^0x[A-Fa-f0-9]+$"),
                        "Enter a valid hex string ",
                        "invalid",
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="tos",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True), ("final", True)),
                fields=("type", "final", "active"),
                name="Only 1 active final tos is allowed for any given type",
            ),
        ),
    ]
