# Generated by Django 4.2.6 on 2024-03-28 19:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tos", "0002_remove_tos_unique_active_tops_for_type_tos_final_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tos",
            options={"permissions": (("activate_tos", "Can activate TOS instances"),)},
        ),
    ]
