# Generated by Django 4.2.6 on 2024-03-18 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stake", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stake",
            name="chain",
            field=models.SmallIntegerField(
                choices=[(0, "Ethereum"), (1, "Optimism")], db_index=True, default=0
            ),
        ),
        migrations.AlterField(
            model_name="stakeevent",
            name="chain",
            field=models.SmallIntegerField(
                choices=[(0, "Ethereum"), (1, "Optimism")], db_index=True
            ),
        ),
    ]
