# Generated by Django 4.2.6 on 2024-03-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stake", "0002_alter_stake_chain_alter_stakeevent_chain"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stake",
            name="chain",
            field=models.IntegerField(db_index=True, help_text="Decimal chain ID"),
        ),
        migrations.AlterField(
            model_name="stakeevent",
            name="chain",
            field=models.IntegerField(db_index=True, help_text="Decimal chain ID"),
        ),
    ]
