# Generated by Django 4.2.6 on 2024-04-16 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stake", "0004_alter_stake_current_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stake",
            name="current_amount",
            field=models.DecimalField(
                decimal_places=18, help_text="Summary stake amount", max_digits=78
            ),
        ),
        migrations.AlterField(
            model_name="stakeevent",
            name="amount",
            field=models.DecimalField(decimal_places=18, max_digits=78),
        ),
    ]
