# Generated by Django 4.2.6 on 2024-07-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stake", "0005_alter_stake_current_amount_alter_stakeevent_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReindexRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chain",
                    models.IntegerField(
                        db_index=True,
                        help_text="Decimal chain ID. Ethereum: 1, Optimism: 10, Arbitrum: 42161",
                    ),
                ),
                (
                    "start_block_number",
                    models.DecimalField(decimal_places=0, max_digits=78),
                ),
                ("pending", models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="stake",
            name="last_updated_in_block",
        ),
        migrations.AlterField(
            model_name="stakeevent",
            name="block_number",
            field=models.DecimalField(db_index=True, decimal_places=0, max_digits=78),
        ),
        migrations.AlterUniqueTogether(
            name="stakeevent",
            unique_together={("tx_hash", "chain")},
        ),
        migrations.AddConstraint(
            model_name="reindexrequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pending", True)),
                fields=("chain",),
                name="unique_only_one_pending_per_chain",
            ),
        ),
    ]
