# Generated by Django 4.2.6 on 2024-07-17 16:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("stake", "0006_reindexrequest_alter_stakeevent_block_number_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stakeevent",
            unique_together={("tx_hash", "chain", "stakee")},
        ),
    ]
