# Generated by Django 4.2.6 on 2024-07-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stake", "0006_reindexrequest_alter_stakeevent_block_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reindexrequest",
            name="chain",
            field=models.IntegerField(
                db_index=True,
                help_text="Decimal chain ID. Ethereum: 1, Optimism: 10, Arbitrum: 42161",
            ),
        ),
    ]
