# Generated by Django 4.1.1 on 2022-10-03 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Passport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("did", models.CharField(max_length=100, unique=True)),
                ("passport", models.JSONField(default=dict)),
                (
                    "version",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="A counter for passport submissions. This records in which passport \n        submission the passport was updated. This will include also submissions when \n        stamps have been removed from this passport as part of de-duping",
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Stamp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "provider",
                    models.CharField(db_index=True, default="", max_length=256),
                ),
                ("credential", models.JSONField(default=dict)),
                (
                    "passport",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stamps",
                        to="registry.passport",
                    ),
                ),
            ],
        ),
    ]
