# Generated by Django 4.1.1 on 2022-09-29 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stamp",
            old_name="stamp_id",
            new_name="hash",
        ),
    ]
