# Generated by Django 4.1.3 on 2022-11-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='version',
            field=models.BigIntegerField(blank=True, db_index=True, help_text='A counter for passport submissions. This records in which passport\n        submission the passport was updated. This will include also submissions when\n        stamps have been removed from this passport as part of de-duping', null=True),
        ),
    ]
