# Generated by Django 4.1.4 on 2022-12-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_community_scorer"),
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="score",
            name="scorer",
        ),
        migrations.AddField(
            model_name="passport",
            name="address",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="passport",
            unique_together={("address", "community")},
        ),
        migrations.RemoveField(
            model_name="passport",
            name="did",
        ),
    ]
