# Generated by Django 4.1.4 on 2022-12-14 09:09

import account.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0002_remove_score_scorer_passport_address_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passport",
            name="version",
        ),
        migrations.AlterField(
            model_name="passport",
            name="address",
            field=account.models.EthAddressField(max_length=100, null=True),
        ),
    ]
