# Generated by Django 4.1.3 on 2022-12-07 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_community_options_alter_account_user'),
        ('registry', '0002_alter_passport_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='account.community'),
        ),
    ]
