# Generated by Django 4.1.4 on 2022-12-15 09:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0003_remove_passport_version_alter_passport_address"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stamp",
            unique_together={("hash", "passport")},
        ),
        migrations.RemoveField(
            model_name="stamp",
            name="community",
        ),
    ]
