# Generated by Django 4.1.4 on 2022-12-07 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_community_options_alter_account_user'),
        ('registry', '0003_passport_community'),
    ]

    operations = [
        migrations.AddField(
            model_name='stamp',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stamps', to='account.community'),
        ),
        migrations.AlterField(
            model_name='stamp',
            name='hash',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='stamp',
            unique_together={('hash', 'community')},
        ),
    ]
