# Generated by Django 4.1.5 on 2023-01-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0004_alter_stamp_unique_together_remove_stamp_community"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="error",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="score",
            name="last_score_timestamp",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="score",
            name="status",
            field=models.CharField(
                choices=[
                    ("PROCESSING", "PROCESSING"),
                    ("DONE", "DONE"),
                    ("ERROR", "ERROR"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
    ]
