# Generated by Django 4.1.5 on 2023-01-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0005_score_error_score_last_score_timestamp_score_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="evidence",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
