# Generated by Django 4.1.5 on 2023-01-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0006_score_evidence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passport",
            name="passport",
            field=models.JSONField(default=dict, null=True),
        ),
    ]
