# Generated by Django 4.1.7 on 2023-03-27 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0007_alter_passport_passport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passport",
            name="passport",
        ),
    ]
