# Generated by Django 4.1.7 on 2023-04-24 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0008_remove_passport_passport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="passport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="score",
                to="registry.passport",
                unique=True,
            ),
        ),
    ]
