# Generated by Django 4.2 on 2023-06-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0009_alter_score_passport"),
    ]

    operations = [
        migrations.AddField(
            model_name="passport",
            name="requires_calculation",
            field=models.BooleanField(
                help_text="This flag indicates that this passport requires calculation of the score. The score calculation task shall skip calculation unless this flag is set.",
                null=True,
            ),
        ),
    ]
