# Generated by Django 4.2.3 on 2023-07-19 15:34

from django.db import migrations, models

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0012_alter_score_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("FDP", "Fifo Deduplication"),
                            ("LDP", "Lifo Deduplication"),
                        ],
                        max_length=3,
                    ),
                ),
                ("address", account.models.EthAddressField(blank=True, max_length=42)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("data", models.JSONField()),
            ],
        ),
    ]
