# Generated by Django 4.2.3 on 2023-07-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0012_alter_score_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="last_score_timestamp",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
    ]
