# Generated by Django 4.2.3 on 2023-07-24 21:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0013_alter_score_last_score_timestamp"),
        ("registry", "0013_event"),
    ]

    operations = []
