# Generated by Django 4.2.3 on 2023-08-03 23:21

import account.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0016_accountapikey_create_scorers_and_more"),
        ("registry", "0014_merge_20230724_2144"),
    ]

    operations = [
        migrations.CreateModel(
            name="HashScorerLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hash", models.CharField(db_index=True, max_length=100)),
                (
                    "address",
                    account.models.EthAddressField(db_index=True, max_length=42),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="burned_hashes",
                        to="account.community",
                    ),
                ),
            ],
            options={
                "unique_together": {("hash", "community")},
            },
        ),
    ]
