# Generated by Django 4.2.3 on 2023-08-24 11:17

from django.db import migrations, models

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0015_hashscorerlink"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="action",
            field=models.CharField(
                choices=[
                    ("FDP", "Fifo Deduplication"),
                    ("LDP", "Lifo Deduplication"),
                    ("TLS", "Trustalab Score"),
                ],
                db_index=True,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="address",
            field=account.models.EthAddressField(
                blank=True, db_index=True, max_length=42
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="data",
            field=models.JSONField(db_index=True),
        ),
    ]
