# Generated by Django 4.2.4 on 2023-09-14 20:51

from django.db import migrations, models

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0016_alter_event_action_alter_event_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="context",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="action",
            field=models.CharField(
                choices=[
                    ("FDP", "Fifo Deduplication"),
                    ("LDP", "Lifo Deduplication"),
                    ("TLS", "Trustalab Score"),
                    ("SCU", "Score Update"),
                ],
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="address",
            field=account.models.EthAddressField(blank=True, max_length=42),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="data",
            field=models.JSONField(),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["action", "address", "context", "created_at"],
                name="event_index",
            ),
        ),
    ]
