# Generated by Django 4.2.4 on 2023-09-15 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0016_accountapikey_create_scorers_and_more"),
        (
            "registry",
            "0017_event_context_alter_event_action_alter_event_address_and_more",
        ),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="event",
            name="event_index",
        ),
        migrations.RemoveField(
            model_name="event",
            name="context",
        ),
        migrations.AddField(
            model_name="event",
            name="community",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event",
                to="account.community",
            ),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                fields=["action", "address", "community", "created_at"],
                name="event_index",
            ),
        ),
    ]
