# Generated by Django 4.2.4 on 2023-09-15 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0018_remove_event_event_index_remove_event_context_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="event",
            new_name="score_history_index",
            old_name="event_index",
        ),
    ]
