# Generated by Django 4.2.4 on 2023-09-18 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0016_accountapikey_create_scorers_and_more"),
        ("registry", "0020_alter_event_community"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="community",
            field=models.ForeignKey(
                default=None,
                help_text="\nThis field is only used for the SCORE_UPDATE action, and will identify the scorer (alias `community`)\nfor which a score has been updated.\nThe reason to have this field (and not use the `data` JSON field) is to be able to easily have an index for the community_id for faster lookups.\n",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event",
                to="account.community",
            ),
        ),
    ]
