# Generated by Django 4.2.4 on 2023-09-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0021_alter_event_community"),
    ]

    operations = [
        migrations.AddField(
            model_name="stamp",
            name="points",
            field=models.DecimalField(
                blank=True, decimal_places=9, default=0, max_digits=18, null=True
            ),
        ),
    ]
