# Generated by Django 4.2.4 on 2023-10-13 20:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0022_stamp_points_squashed_0024_alter_score_points"),
    ]

    operations = [
        migrations.RenameField(
            model_name="score",
            old_name="points",
            new_name="stamp_scores",
        ),
    ]
