# Generated by Django 4.2.6 on 2023-10-25 18:28

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0025_rename_points_score_stamp_scores"),
    ]

    operations = [
        migrations.CreateModel(
            name="GTCStakeEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=15)),
                ("round_id", models.IntegerField()),
                ("staker", account.models.EthAddressField(blank=True, max_length=42)),
                ("address", account.models.EthAddressField(blank=True, max_length=42)),
                ("amount", models.CharField(max_length=42)),
                ("staked", models.BooleanField()),
                ("block_number", models.IntegerField()),
                ("tx_hash", models.CharField(max_length=66)),
            ],
        ),
    ]
