# Generated by Django 4.2.6 on 2023-10-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0025_rename_points_score_stamp_scores"),
    ]

    operations = [
        migrations.CreateModel(
            name="GTCStakeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=15)),
                ("round_id", models.IntegerField()),
                ("staker", models.CharField(max_length=42)),
                ("address", models.CharField(blank=True, max_length=42, null=True)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=78)),
                ("staked", models.BooleanField()),
                ("block_number", models.IntegerField()),
                ("tx_hash", models.CharField(max_length=66)),
            ],
            options={
                "db_table": "gtcstakeevents",
                "managed": True,
            },
        ),
    ]
