# Generated by Django 4.2.6 on 2023-10-31 12:30

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0025_rename_points_score_stamp_scores"),
    ]

    operations = [
        migrations.CreateModel(
            name="GTCStakeEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=15)),
                ("round_id", models.IntegerField(db_index=True)),
                (
                    "staker",
                    account.models.EthAddressField(db_index=True, max_length=42),
                ),
                (
                    "address",
                    account.models.EthAddressField(
                        db_index=True, max_length=42, null=True
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=0, max_digits=78)),
                ("staked", models.BooleanField()),
                ("block_number", models.IntegerField()),
                ("tx_hash", models.CharField(max_length=66)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["round_id", "address", "staker"],
                        name="gtc_staking_index",
                    )
                ],
            },
        ),
    ]
