# Generated by Django 4.2.6 on 2023-11-01 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0026_gtcstakeevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gtcstakeevent",
            name="amount",
            field=models.DecimalField(decimal_places=18, max_digits=78),
        ),
    ]
