# Generated by Django 4.2.6 on 2023-10-26 11:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0026_gtcstakeevents"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gtcstakeevents",
            options={"managed": False},
        ),
    ]
