# Generated by Django 4.2.6 on 2023-11-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0027_alter_gtcstakeevent_amount"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="gtcstakeevent",
            index=models.Index(
                fields=["round_id", "staker"], name="gtc_staking_index_by_staker"
            ),
        ),
    ]
