# Generated by Django 4.2.6 on 2023-10-26 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0027_alter_gtcstakeevents_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="gtcstakeevents",
            options={"managed": True},
        ),
    ]
