# Generated by Django 4.2.6 on 2024-02-05 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0018_alter_community_unique_together_and_more"),
        ("registry", "0028_gtcstakeevent_gtc_staking_index_by_staker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="community",
            field=models.ForeignKey(
                default=None,
                help_text="\nThis field is only used for the SCORE_UPDATE and Deduplication events.\nThe reason to have this field (and not use the `data` JSON field) is to be able to easily have an index for the community_id for faster lookups.\n",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event",
                to="account.community",
            ),
        ),
    ]
