# Generated by Django 4.2.6 on 2024-02-13 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0029_alter_event_community"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="score",
            options={
                "permissions": [
                    ("rescore_individual_score", "Can rescore individual scores")
                ]
            },
        ),
    ]
