# Generated by Django 4.2.6 on 2024-03-06 18:29

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0030_alter_score_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chain",
                    models.SmallIntegerField(
                        choices=[("0", "Ethereum Mainnet"), ("1", "Optimism Mainnet")],
                        db_index=True,
                        default="0",
                    ),
                ),
                ("unlock_time", models.DateTimeField()),
                (
                    "last_updated_in_block",
                    models.DecimalField(decimal_places=0, max_digits=78),
                ),
                (
                    "staker",
                    account.models.EthAddressField(db_index=True, max_length=42),
                ),
                (
                    "stakee",
                    account.models.EthAddressField(db_index=True, max_length=42),
                ),
                (
                    "current_amount",
                    models.DecimalField(decimal_places=0, max_digits=78),
                ),
            ],
            options={
                "unique_together": {("chain", "staker", "stakee")},
            },
        ),
    ]
