# Generated by Django 4.2.6 on 2024-03-14 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0031_stakeevent_stake"),
    ]

    operations = [
        migrations.AddField(
            model_name="stake",
            name="lock_duration",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
