# Generated by Django 4.2.6 on 2024-06-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0032_delete_stake_delete_stakeevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="score",
            name="expiration_date",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, null=True
            ),
        ),
    ]
