# Generated by Django 4.2.6 on 2024-08-02 22:24

from django.db import migrations, models

import registry.models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0033_score_expiration_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchModelScoringRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("s3_filename", models.CharField(max_length=100)),
                ("model_list", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", registry.models.BatchRequestStatus["PENDING"]),
                            ("DONE", registry.models.BatchRequestStatus["DONE"]),
                        ],
                        default=registry.models.BatchRequestStatus["PENDING"],
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
