# Generated by Django 4.2.6 on 2024-08-07 20:39

from django.db import migrations, models

import registry.models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0034_batchmodelscoringrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchmodelscoringrequest",
            name="progress",
            field=models.IntegerField(
                default=0, help_text="Progress in percentage: 0-100"
            ),
        ),
        migrations.AlterField(
            model_name="batchmodelscoringrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", registry.models.BatchRequestStatus["PENDING"]),
                    ("DONE", registry.models.BatchRequestStatus["DONE"]),
                    ("ERROR", registry.models.BatchRequestStatus["ERROR"]),
                ],
                default=registry.models.BatchRequestStatus["PENDING"],
                max_length=10,
            ),
        ),
    ]
