# Generated by Django 4.2.6 on 2024-08-15 14:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    replaces = [
        ("registry", "0036_weightconfiguration_weightconfigurationitem_and_more"),
        ("registry", "0037_alter_weightconfigurationitem_weight"),
        ("registry", "0038_remove_weightconfiguration_description_and_more"),
        ("registry", "0039_remove_weightconfiguration_threshold"),
        ("registry", "0040_weightconfiguration_threshold"),
    ]

    dependencies = [
        ("registry", "0035_batchmodelscoringrequest_progress_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeightConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=50, unique=True)),
                (
                    "threshold",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeightConfigurationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=100)),
                (
                    "weight",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ]
                    ),
                ),
                (
                    "weight_configuration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weights",
                        to="registry.weightconfiguration",
                    ),
                ),
            ],
            options={
                "ordering": ["provider"],
            },
        ),
        migrations.AddConstraint(
            model_name="weightconfiguration",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("active",),
                name="unique_active_weight_configuration",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="weightconfigurationitem",
            unique_together={("weight_configuration", "provider")},
        ),
        migrations.AlterField(
            model_name="weightconfigurationitem",
            name="weight",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(100),
                ]
            ),
        ),
        migrations.RemoveField(
            model_name="weightconfiguration",
            name="description",
        ),
        migrations.RemoveField(
            model_name="weightconfiguration",
            name="threshold",
        ),
        migrations.AddField(
            model_name="weightconfiguration",
            name="threshold",
            field=models.FloatField(
                default=20.0,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1000),
                ],
            ),
        ),
    ]
