# Generated by Django 4.2.6 on 2024-08-16 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "registry",
            "0036_weightconfiguration_weightconfigurationitem_and_more_squashed_0040_weightconfiguration_threshold",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="weightconfiguration",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
