# Generated by Django 4.2.6 on 2025-03-05 06:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0042_score_stamps"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="stamp",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="stamp",
            name="hash",
        ),
    ]
