# Generated by Django 4.2.6 on 2025-04-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0043_alter_stamp_unique_together_remove_stamp_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightconfiguration",
            name="csv_source",
            field=models.FileField(
                blank=True, default=None, null=True, upload_to="weight_configurations/"
            ),
        ),
    ]
