# Generated by Django 4.2.6 on 2025-05-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0044_weightconfiguration_csv_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchmodelscoringrequest",
            name="s3_file",
            field=models.FileField(
                blank=True, null=True, upload_to="registr_batch_model_scoring"
            ),
        ),
        migrations.AlterField(
            model_name="batchmodelscoringrequest",
            name="s3_filename",
            field=models.CharField(
                help_text="This field has been deprecated", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="weightconfiguration",
            name="csv_source",
            field=models.FileField(
                blank=True,
                default=None,
                help_text="CSV file containing weight configuration",
                null=True,
                upload_to="weight_configurations/",
            ),
        ),
        migrations.AlterField(
            model_name="weightconfiguration",
            name="version",
            field=models.CharField(
                blank=True,
                help_text="Leave empty to generate version automatically",
                max_length=50,
                unique=True,
            ),
        ),
    ]
