# Generated by Django 4.2.6 on 2025-06-04 09:40

from django.db import migrations, models

import registry.models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0046_remove_batchmodelscoringrequest_s3_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="batchmodelscoringrequest",
            name="input_addresses_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="batch_model_scoreing_request/address-lists",
            ),
        ),
        migrations.AddField(
            model_name="batchmodelscoringrequest",
            name="results_file",
            field=models.FileField(
                blank=True,
                help_text="Will contain the exported data",
                null=True,
                upload_to="batch_model_score_request",
            ),
        ),
        migrations.AlterField(
            model_name="batchmodelscoringrequest",
            name="s3_filename",
            field=models.CharField(
                db_index=True,
                help_text="This is deprecated, in favour of `input_addresses_file`",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="batchmodelscoringrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", registry.models.BatchRequestStatus["PENDING"]),
                    ("DONE", registry.models.BatchRequestStatus["DONE"]),
                    ("ERROR", registry.models.BatchRequestStatus["ERROR"]),
                    ("IMPORTING", registry.models.BatchRequestStatus["IMPORTING"]),
                    (
                        "IMPORTING_DONE",
                        registry.models.BatchRequestStatus["IMPORTING_DONE"],
                    ),
                    ("SCORING", registry.models.BatchRequestStatus["SCORING"]),
                ],
                default=registry.models.BatchRequestStatus["PENDING"],
                max_length=20,
            ),
        ),
    ]
