# Generated by Django 4.2.6 on 2025-06-06 10:07

from django.db import migrations, models

import registry.models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0047_batchmodelscoringrequest_input_addresses_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchmodelscoringrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", registry.models.BatchRequestStatus["PENDING"]),
                    ("DONE", registry.models.BatchRequestStatus["DONE"]),
                    ("ERROR", registry.models.BatchRequestStatus["ERROR"]),
                ],
                db_index=True,
                default=registry.models.BatchRequestStatus["PENDING"],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="batchmodelscoringrequestitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", registry.models.BatchRequestItemStatus["PENDING"]),
                    ("DONE", registry.models.BatchRequestItemStatus["DONE"]),
                    ("ERROR", registry.models.BatchRequestItemStatus["ERROR"]),
                ],
                db_index=True,
                default=registry.models.BatchRequestItemStatus["PENDING"],
                max_length=20,
            ),
        ),
    ]
