# Generated by Django 4.2.6 on 2025-06-04 16:38

import django.db.models.deletion
from django.db import migrations, models

import account.models
import registry.models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0047_batchmodelscoringrequest_input_addresses_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchmodelscoringrequest",
            name="input_addresses_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=registry.models.input_addresses_file_upload_to,
            ),
        ),
        migrations.AlterField(
            model_name="batchmodelscoringrequest",
            name="progress",
            field=models.IntegerField(
                default=0, help_text="Progress in percentage: 0-100 ---- DEPRECATED ???"
            ),
        ),
        migrations.AlterField(
            model_name="batchmodelscoringrequest",
            name="results_file",
            field=models.FileField(
                blank=True,
                help_text="Will contain the exported data",
                null=True,
                upload_to=registry.models.results_file_upload_to,
            ),
        ),
        migrations.CreateModel(
            name="BatchModelScoringRequestItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", registry.models.BatchRequestStatus["PENDING"]),
                            ("DONE", registry.models.BatchRequestStatus["DONE"]),
                            ("ERROR", registry.models.BatchRequestStatus["ERROR"]),
                            (
                                "IMPORTING",
                                registry.models.BatchRequestStatus["IMPORTING"],
                            ),
                            (
                                "IMPORTING_DONE",
                                registry.models.BatchRequestStatus["IMPORTING_DONE"],
                            ),
                            ("SCORING", registry.models.BatchRequestStatus["SCORING"]),
                        ],
                        default=registry.models.BatchRequestStatus["PENDING"],
                        max_length=20,
                    ),
                ),
                (
                    "address",
                    account.models.EthAddressField(db_index=True, max_length=42),
                ),
                ("result", models.JSONField(blank=True, default=None, null=True)),
                (
                    "batch_scoring_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="registry.batchmodelscoringrequest",
                    ),
                ),
            ],
        ),
    ]
