# Generated by Django 4.2.6 on 2025-06-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0048_alter_batchmodelscoringrequest_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HumanPointProgramStats",
            fields=[
                (
                    "address",
                    models.CharField(
                        db_index=True, max_length=100, primary_key=True, serialize=False
                    ),
                ),
                ("passing_scores", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Human Point Program Stats",
                "verbose_name_plural": "Human Point Program Stats",
            },
        ),
        migrations.CreateModel(
            name="HumanPointsMultiplier",
            fields=[
                (
                    "address",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("multiplier", models.IntegerField(default=2)),
            ],
            options={
                "verbose_name": "Human Points Multiplier",
                "verbose_name_plural": "Human Points Multipliers",
            },
        ),
        migrations.CreateModel(
            name="HumanPoints",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(db_index=True, max_length=100)),
                ("action", models.CharField(max_length=50)),
                ("points", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("tx_hash", models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                "verbose_name": "Human Point",
                "verbose_name_plural": "Human Points",
                "indexes": [
                    models.Index(
                        fields=["address", "action"],
                        name="registry_hu_address_5fea1a_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="registry_hu_timesta_7c6e55_idx"
                    ),
                ],
            },
        ),
    ]
