# Generated by Django 4.2.6 on 2025-06-04 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "registry",
            "0048_alter_batchmodelscoringrequest_input_addresses_file_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchmodelscoringrequestitem",
            name="batch_scoring_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="items",
                to="registry.batchmodelscoringrequest",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="batchmodelscoringrequestitem",
            unique_together={("batch_scoring_request", "address")},
        ),
    ]
