# Generated by Django 4.2.6
from django.db import migrations


def populate_human_points_config(apps, schema_editor):
    """Populate initial HumanPointsConfig data"""
    HumanPointsConfig = apps.get_model("registry", "HumanPointsConfig")

    configs = [
        ("SCB", 500),  # SCORING_BONUS
        ("HKY", 100),  # HUMAN_KEYS
        ("ISB", 100),  # IDENTITY_STAKING_BRONZE
        ("ISS", 200),  # IDENTITY_STAKING_SILVER
        ("ISG", 500),  # IDENTITY_STAKING_GOLD
        ("CSB", 100),  # COMMUNITY_STAKING_BEGINNER
        ("CSE", 200),  # COMMUNITY_STAKING_EXPERIENCED
        ("CST", 500),  # COMMUNITY_STAKING_TRUSTED
        ("PMT", 300),  # PASSPORT_MINT
        ("HIM", 1000),  # HUMAN_ID_MINT
    ]

    for action, points in configs:
        HumanPointsConfig.objects.get_or_create(
            action=action, defaults={"points": points, "active": True}
        )


def reverse_populate_human_points_config(apps, schema_editor):
    """Remove initial HumanPointsConfig data"""
    HumanPointsConfig = apps.get_model("registry", "HumanPointsConfig")
    HumanPointsConfig.objects.filter(
        action__in=[
            "SCB",
            "HKY",
            "ISB",
            "ISS",
            "ISG",
            "CSB",
            "CSE",
            "CST",
            "PMT",
            "HIM",
        ]
    ).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0049_humanpoints_models"),
    ]

    operations = [
        migrations.RunPython(
            populate_human_points_config, reverse_populate_human_points_config
        ),
    ]
