# Generated by Django 4.2.6 on 2025-06-20 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0042_community_human_points_program"),
        ("registry", "0050_humanpoints_unique_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="HumanPointProgramScores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(db_index=True, max_length=100)),
                (
                    "community",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="human_point_scores",
                        to="account.community",
                    ),
                ),
            ],
            options={
                "verbose_name": "Human Point Program Score",
                "verbose_name_plural": "Human Point Program Scores",
            },
        ),
        migrations.DeleteModel(
            name="HumanPointProgramStats",
        ),
        migrations.AddField(
            model_name="humanpoints",
            name="chain_id",
            field=models.IntegerField(
                blank=True, help_text="Chain ID for mint actions", null=True
            ),
        ),
        migrations.AddField(
            model_name="humanpoints",
            name="community_id",
            field=models.IntegerField(
                blank=True, help_text="Community ID for mint actions", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="humanpointprogramscores",
            index=models.Index(
                fields=["address"], name="registry_hu_address_93e8fe_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="humanpointprogramscores",
            unique_together={("address", "community")},
        ),
    ]
