# Generated by Django 4.2.6 on 2025-06-23 13:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0051_human_points_refactor"),
    ]

    operations = [
        migrations.CreateModel(
            name="HumanPointsConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=50, unique=True)),
                ("points", models.IntegerField()),
                ("active", models.BooleanField(default=True)),
                (
                    "effective_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name": "Human Points Configuration",
                "verbose_name_plural": "Human Points Configurations",
            },
        ),
        migrations.RemoveField(
            model_name="humanpoints",
            name="chain_id",
        ),
        migrations.RemoveField(
            model_name="humanpoints",
            name="community_id",
        ),
        migrations.RemoveField(
            model_name="humanpoints",
            name="points",
        ),
        migrations.AlterField(
            model_name="humanpoints",
            name="action",
            field=models.CharField(
                choices=[
                    ("SCB", "Scoring Bonus"),
                    ("HKY", "Human Keys"),
                    ("ISB", "Identity Staking Bronze"),
                    ("ISS", "Identity Staking Silver"),
                    ("ISG", "Identity Staking Gold"),
                    ("CSB", "Community Staking Beginner"),
                    ("CSE", "Community Staking Experienced"),
                    ("CST", "Community Staking Trusted"),
                    ("PMT", "Passport Mint"),
                    ("HIM", "Human Id Mint"),
                ],
                db_index=True,
                max_length=3,
            ),
        ),
        migrations.AddIndex(
            model_name="humanpoints",
            index=models.Index(
                fields=["address", "timestamp"], name="registry_hu_address_642c68_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="humanpointsconfig",
            index=models.Index(
                fields=["action", "active"], name="registry_hu_action_230641_idx"
            ),
        ),
    ]
