# Generated by Django 4.2.6 on 2025-07-01 07:41

from django.db import migrations, models

import account.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "registry",
            "0051_rename_registry_hu_chain_id_action_idx_registry_hu_chain_i_646b64_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="humanpoints",
            name="address",
            field=account.models.EthAddressField(db_index=True, max_length=42),
        ),
        migrations.AlterField(
            model_name="humanpointscommunityqualifiedusers",
            name="address",
            field=account.models.EthAddressField(db_index=True, max_length=42),
        ),
        migrations.AlterField(
            model_name="humanpointsconfig",
            name="active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="humanpointsmultiplier",
            name="address",
            field=account.models.EthAddressField(
                max_length=42, primary_key=True, serialize=False
            ),
        ),
    ]
