# Generated by Django 4.2.6 on 2025-06-23 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0042_community_human_points_program"),
        ("registry", "0052_humanpointsconfig_remove_humanpoints_chain_id_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HumanPointProgramScores",
            new_name="HumanPointsCommunityQualifiedUsers",
        ),
        migrations.AlterModelOptions(
            name="humanpointscommunityqualifiedusers",
            options={
                "verbose_name": "Human Points Community Qualified User",
                "verbose_name_plural": "Human Points Community Qualified Users",
            },
        ),
        migrations.AlterField(
            model_name="humanpointscommunityqualifiedusers",
            name="community",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="human_points_qualified_users",
                to="account.community",
            ),
        ),
    ]
