# Generated by Django 4.2.6 on 2025-07-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0052_alter_humanpoints_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="humanpointsconfig",
            name="action",
            field=models.CharField(
                choices=[
                    ("SCB", "Scoring Bonus"),
                    ("HKY", "Human Keys"),
                    ("ISB", "Identity Staking Bronze"),
                    ("ISS", "Identity Staking Silver"),
                    ("ISG", "Identity Staking Gold"),
                    ("CSB", "Community Staking Beginner"),
                    ("CSE", "Community Staking Experienced"),
                    ("CST", "Community Staking Trusted"),
                    ("PMT", "Passport Mint"),
                    ("HIM", "Human Id Mint"),
                ],
                db_index=True,
                max_length=50,
                unique=True,
            ),
        ),
    ]
