# Generated by Django 4.2.6 on 2025-06-23 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0053_rename_humanpointprogramscores"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="humanpointscommunityqualifiedusers",
            new_name="registry_hu_address_0abb23_idx",
            old_name="registry_hu_address_93e8fe_idx",
        ),
        migrations.RemoveField(
            model_name="humanpointsconfig",
            name="effective_date",
        ),
    ]
