# Generated by Django 4.2.6 on 2025-07-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0053_alter_humanpointsconfig_action"),
    ]

    operations = [
        migrations.AddField(
            model_name="humanpoints",
            name="provider",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="Provider is relevant to track the human key points",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="humanpoints",
            name="action",
            field=models.CharField(
                choices=[
                    ("SCB", "Scoring Bonus"),
                    ("HKY", "Human Keys"),
                    ("ISB", "Identity Staking Bronze"),
                    ("ISS", "Identity Staking Silver"),
                    ("ISG", "Identity Staking Gold"),
                    ("CSB", "Community Staking Beginner"),
                    ("CSE", "Community Staking Experienced"),
                    ("CST", "Community Staking Trusted"),
                    ("PMT", "Passport Mint"),
                    ("HIM", "Human Id Mint"),
                    ("HGO", "Human Tech Gov Id"),
                    ("HPH", "Human Tech Phone"),
                    ("HCH", "Human Tech Proof Of Clean Hands"),
                    ("HBI", "Human Tech Biometric"),
                ],
                db_index=True,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="humanpoints",
            name="chain_id",
            field=models.IntegerField(
                db_index=True,
                default=0,
                help_text="Chain ID for mint actions (PMT, HIM)",
            ),
        ),
        migrations.AlterField(
            model_name="humanpointsconfig",
            name="action",
            field=models.CharField(
                choices=[
                    ("SCB", "Scoring Bonus"),
                    ("HKY", "Human Keys"),
                    ("ISB", "Identity Staking Bronze"),
                    ("ISS", "Identity Staking Silver"),
                    ("ISG", "Identity Staking Gold"),
                    ("CSB", "Community Staking Beginner"),
                    ("CSE", "Community Staking Experienced"),
                    ("CST", "Community Staking Trusted"),
                    ("PMT", "Passport Mint"),
                    ("HIM", "Human Id Mint"),
                    ("HGO", "Human Tech Gov Id"),
                    ("HPH", "Human Tech Phone"),
                    ("HCH", "Human Tech Proof Of Clean Hands"),
                    ("HBI", "Human Tech Biometric"),
                ],
                db_index=True,
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="humanpoints",
            constraint=models.UniqueConstraint(
                fields=("address", "action", "chain_id", "provider"),
                name="unique_human_points_constraint",
            ),
        ),
    ]
