# Generated by Django 4.2.6 on 2025-07-11 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0054_humanpoints_provider_alter_humanpoints_action_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="humanpoints",
            name="unique_human_points_constraint",
        ),
        migrations.AlterField(
            model_name="humanpoints",
            name="tx_hash",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddConstraint(
            model_name="humanpoints",
            constraint=models.UniqueConstraint(
                fields=("address", "action", "chain_id", "provider", "tx_hash"),
                name="unique_human_points_constraint",
            ),
        ),
        # Add unique constraints for HumanPoints
        # Unique constraint for binary actions (stamps, staking) - excluding HKY since it needs tx_hash
        migrations.RunSQL(
            "DROP INDEX IF EXISTS idx_binary_actions;",
            reverse_sql="",
        ),
        # Unique constraint for actions that require tx_hash (mints and human keys)
        migrations.RunSQL(
            "DROP INDEX IF EXISTS idx_tx_hash_actions;",
            reverse_sql="",
        ),
    ]
