# Generated by Django 4.2.6 on 2025-08-19 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registry", "0055_remove_humanpoints_unique_human_points_constraint_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="humanpoints",
            name="action",
            field=models.CharField(
                choices=[
                    ("SCB", "Scoring Bonus"),
                    ("HKY", "Human Keys"),
                    ("ISB", "Identity Staking Bronze"),
                    ("ISS", "Identity Staking Silver"),
                    ("ISG", "Identity Staking Gold"),
                    ("CSB", "Community Staking Beginner"),
                    ("CSE", "Community Staking Experienced"),
                    ("CST", "Community Staking Trusted"),
                    ("PMT", "Passport Mint"),
                    ("HIM", "Human Id Mint"),
                    ("HGO", "Human Tech Gov Id"),
                    ("HPH", "Human Tech Phone"),
                    ("HCH", "Human Tech Proof Of Clean Hands"),
                    ("HBI", "Human Tech Biometric"),
                    ("MTA", "Metamask Og"),
                ],
                db_index=True,
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="humanpointsconfig",
            name="action",
            field=models.CharField(
                choices=[
                    ("SCB", "Scoring Bonus"),
                    ("HKY", "Human Keys"),
                    ("ISB", "Identity Staking Bronze"),
                    ("ISS", "Identity Staking Silver"),
                    ("ISG", "Identity Staking Gold"),
                    ("CSB", "Community Staking Beginner"),
                    ("CSE", "Community Staking Experienced"),
                    ("CST", "Community Staking Trusted"),
                    ("PMT", "Passport Mint"),
                    ("HIM", "Human Id Mint"),
                    ("HGO", "Human Tech Gov Id"),
                    ("HPH", "Human Tech Phone"),
                    ("HCH", "Human Tech Proof Of Clean Hands"),
                    ("HBI", "Human Tech Biometric"),
                    ("MTA", "Metamask Og"),
                ],
                db_index=True,
                max_length=50,
                unique=True,
            ),
        ),
    ]
