# Generated by Django 4.1.4 on 2022-12-09 14:25

import django.db.models.deletion
from django.db import migrations, models

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ("scorer_weighted", "0001_initial"),
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="scorer",
            field=models.ForeignKey(
                default=account.models.get_default_community_scorer,
                on_delete=django.db.models.deletion.PROTECT,
                to="scorer_weighted.scorer",
            ),
        ),
    ]
