# Generated by Django 4.1.4 on 2022-12-12 09:04

from django.db import migrations, models

import account.deduplication


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_alter_community_scorer"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="rules",
            field=models.CharField(
                choices=[
                    (account.deduplication.Rules["LIFO"], "LIFO"),
                    (account.deduplication.Rules["FIFO"], "FIFO"),
                ],
                default=account.deduplication.Rules["LIFO"],
                max_length=100,
            ),
        ),
    ]
