# Generated by Django 4.1.4 on 2022-12-16 08:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_alter_account_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="Nonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nonce", models.CharField(max_length=60, unique=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("was_used", models.BooleanField(default=False)),
            ],
        ),
    ]
