# Generated by Django 4.1.3 on 2022-12-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_community'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Community',
            new_name='Communities',
        ),
    ]
