# Generated by Django 4.1.3 on 2022-12-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_community_communities'),
    ]

    operations = [
        migrations.AddField(
            model_name='communities',
            name='description',
            field=models.CharField(default='My community', max_length=100),
        ),
    ]
