# Generated by Django 4.1.4 on 2022-12-19 18:22

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_nonce"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="address",
            field=account.models.EthAddressField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="nonce",
            name="nonce",
            field=models.CharField(db_index=True, max_length=60, unique=True),
        ),
    ]
