# Generated by Django 4.1.3 on 2022-12-05 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_communities_description"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Communities",
            new_name="Community",
        ),
    ]
