# Generated by Django 4.1.5 on 2023-01-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0006_alter_account_address_alter_nonce_nonce"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonce",
            name="expires_on",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
