# Generated by Django 4.1.7 on 2023-03-02 13:00

import account.deduplication
import account.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("scorer_weighted", "0002_alter_binaryweightedscorer_threshold"),
        ("account", "0007_nonce_expires_on"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="community",
            name="rules",
        ),
        migrations.AddField(
            model_name="community",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="community",
            name="rule",
            field=models.CharField(
                choices=[("LIFO", "LIFO"), ("FIFO", "FIFO")],
                default=account.deduplication.Rules["LIFO"],
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="use_case",
            field=models.CharField(
                blank=True,
                help_text="The use case that the creator of this community (Scorer) would like to cover",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="scorer",
            field=models.ForeignKey(
                default=account.models.get_default_community_scorer,
                on_delete=django.db.models.deletion.CASCADE,
                to="scorer_weighted.scorer",
            ),
        ),
    ]
