# Generated by Django 4.1.5 on 2023-01-31 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0007_nonce_expires_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="nonce",
            name="address",
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
    ]
