# Generated by Django 4.1.6 on 2023-02-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_nonce_expires_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="use_case",
            field=models.CharField(
                blank=True,
                help_text="The use case that the creator of this community (Scorer) would like to cover",
                max_length=100,
                null=True,
            ),
        ),
    ]
