# Generated by Django 4.1.7 on 2023-03-01 07:33

import account.deduplication
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_nonce_expires_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="community",
            name="use_case",
            field=models.CharField(
                blank=True,
                help_text="The use case that the creator of this community (Scorer) would like to cover",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="community",
            name="rules",
            field=models.CharField(
                choices=[("LIFO", "LIFO"), ("FIFO", "FIFO")],
                default=account.deduplication.Rules["LIFO"],
                max_length=100,
            ),
        ),
    ]
