# Generated by Django 4.1.7 on 2023-03-14 08:44

import account.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_alter_community_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountapikey",
            name="rate_limit",
            field=models.CharField(
                choices=[
                    ("125/15m", account.models.RateLimits["TIER_1"]),
                    ("350/15m", account.models.RateLimits["TIER_2"]),
                    ("2000/15m", account.models.RateLimits["TIER_3"]),
                ],
                default="125/15m",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="accountapikey",
            name="account",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="api_keys",
                to="account.account",
            ),
        ),
    ]
