# Generated by Django 4.1.6 on 2023-03-13 22:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_community_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2023, 3, 13, 22, 55, 38, 286553, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
