# Generated by Django 4.1.6 on 2023-03-02 12:45

import account.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scorer_weighted", "0002_alter_binaryweightedscorer_threshold"),
        ("account", "0009_remove_community_rules_community_rule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="scorer",
            field=models.ForeignKey(
                default=account.models.get_default_community_scorer,
                on_delete=django.db.models.deletion.CASCADE,
                to="scorer_weighted.scorer",
            ),
        ),
    ]
