# Generated by Django 4.1.6 on 2023-03-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_alter_community_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
