# Generated by Django 4.1.7 on 2023-03-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0011_alter_community_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="community",
            name="rule",
            field=models.CharField(
                choices=[("LIFO", "LIFO"), ("FIFO", "FIFO")],
                default="LIFO",
                max_length=100,
            ),
        ),
    ]
