# Generated by Django 4.1.7 on 2023-03-30 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0012_alter_community_rule"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="community",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="community",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="community",
            unique_together={("account", "name", "deleted_at")},
        ),
    ]
