# Generated by Django 4.1.7 on 2023-03-29 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0012_alter_community_rule"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountAPIKeyAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_count", models.IntegerField(default=0)),
                ("path", models.CharField(max_length=100)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="account.accountapikey",
                    ),
                ),
            ],
        ),
    ]
