# Generated by Django 4.1.7 on 2023-03-31 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "account",
            "0013_alter_community_unique_together_community_deleted_at_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountAPIKeyAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("path", models.CharField(default="/", max_length=100)),
                (
                    "api_key",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="account.accountapikey",
                    ),
                ),
            ],
        ),
    ]
