# Generated by Django 4.1.7 on 2023-03-29 23:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0013_accountapikeyanalytics"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountapikeyanalytics",
            name="path",
        ),
    ]
