# Generated by Django 4.1.7 on 2023-03-31 17:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0014_remove_accountapikeyanalytics_path"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountapikeyanalytics",
            name="request_count",
        ),
        migrations.AddField(
            model_name="accountapikeyanalytics",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="accountapikeyanalytics",
            name="path",
            field=models.CharField(default="/", max_length=100),
        ),
    ]
