# Generated by Django 4.1.7 on 2023-04-21 19:08

from django.db import migrations, models

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0014_accountapikeyanalytics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountapikey",
            name="rate_limit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("125/15m", account.models.RateLimits["TIER_1"]),
                    ("350/15m", account.models.RateLimits["TIER_2"]),
                    ("2000/15m", account.models.RateLimits["TIER_3"]),
                    ("", account.models.RateLimits["UNLIMITED"]),
                ],
                default="125/15m",
                max_length=20,
                null=True,
            ),
        ),
    ]
