# Generated by Django 4.2 on 2023-05-08 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0015_alter_accountapikey_rate_limit"),
    ]

    operations = [
        migrations.CreateModel(
            name="APIKeyPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("submit_passports", models.BooleanField(default=True)),
                ("read_scores", models.BooleanField(default=True)),
                ("create_scorers", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="community",
            name="allo_scorer_id",
            field=models.CharField(blank=True, max_length=42, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="accountapikey",
            name="permissions",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="account.apikeypermissions",
            ),
        ),
    ]
