# Generated by Django 4.2.1 on 2023-05-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0015_alter_accountapikey_rate_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountapikey",
            name="create_scorers",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accountapikey",
            name="read_scores",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="accountapikey",
            name="submit_passports",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="community",
            name="external_scorer_id",
            field=models.CharField(blank=True, max_length=42, null=True, unique=True),
        ),
    ]
