# Generated by Django 4.2 on 2023-06-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0016_accountapikey_create_scorers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="last_logged_ip",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
