# Generated by Django 4.2.6 on 2024-01-30 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0017_remove_dups"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="community",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="community",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("account", "name"),
                name="unique_non_deleted_name_per_account",
            ),
        ),
        migrations.AddConstraint(
            model_name="community",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", False)),
                fields=("account", "name", "deleted_at"),
                name="unique_deleted_name_per_account",
            ),
        ),
    ]
