# Generated by Django 4.2.6 on 2024-02-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0018_alter_community_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountapikeyanalytics",
            name="base_path",
            field=models.CharField(
                blank=True, db_index=True, max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="accountapikeyanalytics",
            name="error",
            field=models.TextField(
                db_index=True, help_text="Error that occured", null=True
            ),
        ),
        migrations.AddField(
            model_name="accountapikeyanalytics",
            name="headers",
            field=models.JSONField(
                help_text="Contains the HTTP headers from the request", null=True
            ),
        ),
        migrations.AddField(
            model_name="accountapikeyanalytics",
            name="path_segments",
            field=models.JSONField(
                db_index=True,
                default=list,
                help_text="Contains the parameters that are passed in the path segments",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="accountapikeyanalytics",
            name="payload",
            field=models.JSONField(
                db_index=True,
                help_text="Contains the payload sent as part of the HTTP request body",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="accountapikeyanalytics",
            name="query_params",
            field=models.JSONField(
                db_index=True,
                help_text="Contains the parameters that are passed in the query (get) parameters",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="accountapikeyanalytics",
            name="response",
            field=models.JSONField(
                help_text="Contains the response, unless response_skipped is set to True",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="accountapikeyanalytics",
            name="response_skipped",
            field=models.BooleanField(
                db_index=True,
                help_text="Indicates that the response response is not filled in this record. This will typically happen for large responses (when reading pages of data)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="accountapikeyanalytics",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="accountapikeyanalytics",
            name="path",
            field=models.CharField(default="/", max_length=1000),
        ),
    ]
