# Generated by Django 4.2 on 2023-05-11 22:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0018_remove_accountapikey_permissions_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="APIKeyPermissions",
        ),
    ]
