# Generated by Django 4.2.6 on 2024-03-27 08:33

import re

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0019_accountapikeyanalytics_base_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nonce",
            name="nonce",
            field=account.models.NonceField(db_index=True, max_length=60, unique=True),
        ),
        migrations.CreateModel(
            name="Customization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=100, unique=True)),
                (
                    "customization_background_1",
                    account.models.RGBAHexColorField(
                        blank=True,
                        help_text="Background color 1",
                        max_length=9,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^#[A-Fa-f0-9]{8}$"),
                                "Enter a valid RGBA color as hex string ",
                                "invalid",
                            )
                        ],
                    ),
                ),
                (
                    "customization_background_2",
                    account.models.RGBAHexColorField(
                        blank=True,
                        help_text="Background color 2",
                        max_length=9,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^#[A-Fa-f0-9]{8}$"),
                                "Enter a valid RGBA color as hex string ",
                                "invalid",
                            )
                        ],
                    ),
                ),
                (
                    "customization_foreground_1",
                    account.models.RGBAHexColorField(
                        blank=True,
                        help_text="Foreground color",
                        max_length=9,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                re.compile("^#[A-Fa-f0-9]{8}$"),
                                "Enter a valid RGBA color as hex string ",
                                "invalid",
                            )
                        ],
                    ),
                ),
                (
                    "logo_image",
                    account.models.ReactNodeField(
                        blank=True, help_text="The logo in SVG format", null=True
                    ),
                ),
                (
                    "logo_caption",
                    account.models.ReactNodeField(
                        blank=True,
                        help_text="The caption as text or react node object",
                        null=True,
                    ),
                ),
                (
                    "logo_background",
                    models.CharField(
                        blank=True,
                        choices=[("DOTS", "Dots"), ("NONE", "None")],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "body_main_text",
                    account.models.ReactNodeField(
                        blank=True, help_text="The body main text", null=True
                    ),
                ),
                (
                    "body_sub_text",
                    account.models.ReactNodeField(
                        blank=True, help_text="The body sub text", null=True
                    ),
                ),
                ("body_action_text", models.TextField(blank=True, null=True)),
                ("body_action_url", models.URLField(blank=True, null=True)),
                (
                    "scorer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="account.community",
                    ),
                ),
            ],
        ),
    ]
