# Generated by Django 4.2.6 on 2024-03-28 20:33

import re

import django.core.validators
from django.db import migrations

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0021_customization_use_custom_dashboard_panel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customization",
            name="customization_background_1",
            field=account.models.RGBHexColorField(
                blank=True,
                help_text="Background color 1. RGB hex value expected, for example `#aaff66`",
                max_length=7,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^#[A-Fa-f0-9]{6}$"),
                        "Enter a valid RGBA color as hex string ",
                        "invalid",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customization",
            name="customization_background_2",
            field=account.models.RGBHexColorField(
                blank=True,
                help_text="Background color 2. RGB hex value expected, for example `#aaff66`",
                max_length=7,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^#[A-Fa-f0-9]{6}$"),
                        "Enter a valid RGBA color as hex string ",
                        "invalid",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customization",
            name="customization_foreground_1",
            field=account.models.RGBHexColorField(
                blank=True,
                help_text="Foreground color. RGB hex value expected, for example `#aaff66`",
                max_length=7,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^#[A-Fa-f0-9]{6}$"),
                        "Enter a valid RGBA color as hex string ",
                        "invalid",
                    )
                ],
            ),
        ),
    ]
