# Generated by Django 4.2.6 on 2024-04-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0022_alter_customization_customization_background_1_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customization",
            name="scorer_panel_title",
            field=models.CharField(
                blank=True,
                help_text="This is the title for the scorer panel",
                max_length=100,
                null=True,
            ),
        ),
    ]
