# Generated by Django 4.2.6 on 2024-04-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0023_customization_scorer_panel_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="customization",
            name="scorer_panel_text",
            field=models.TextField(
                blank=True, help_text="This is the text for the scorer panel", null=True
            ),
        ),
    ]
