# Generated by Django 4.2.6 on 2024-06-11 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0025_addresslist_addresslistmember"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customization",
            name="scorer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT, to="account.community"
            ),
        ),
    ]
