# Generated by Django 4.2.6 on 2024-06-11 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0026_alter_customization_scorer"),
    ]

    operations = [
        migrations.CreateModel(
            name="AllowList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight", models.FloatField(default=0.0)),
                (
                    "address_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="allow_lists",
                        to="account.addresslist",
                    ),
                ),
                (
                    "customization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allow_lists",
                        to="account.customization",
                    ),
                ),
            ],
        ),
    ]
