# Generated by Django 4.2.6 on 2024-06-12 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0027_allowlist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allowlist",
            name="weight",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=7),
        ),
    ]
