# Generated by Django 4.2.6 on 2024-06-14 13:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0028_alter_allowlist_weight"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addresslist",
            name="name",
            field=models.CharField(
                db_index=True,
                max_length=100,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-zA-Z]*$", "Only alphanumeric characters are allowed."
                    )
                ],
            ),
        ),
    ]
