# Generated by Django 4.2.6 on 2024-06-20 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0029_alter_addresslist_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="IncludedChainId",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chain_id", models.CharField(max_length=200)),
                (
                    "customization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="included_chain_ids",
                        to="account.customization",
                    ),
                ),
            ],
            options={
                "unique_together": {("chain_id", "customization")},
            },
        ),
    ]
