# Generated by Django 4.2.6 on 2024-06-27 12:17

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0030_includedchainid"),
    ]

    operations = [
        migrations.AddField(
            model_name="customization",
            name="body_display_info_tooltip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customization",
            name="body_info_tooltip_text",
            field=account.models.ReactNodeField(
                blank=True, help_text="The info tooltip text", null=True
            ),
        ),
        migrations.AddField(
            model_name="customization",
            name="button_action_type",
            field=models.CharField(
                choices=[
                    ("Simple Link", "Simple Link"),
                    ("Onchain Push", "Onchain Push"),
                ],
                default="Simple Link",
                max_length=25,
            ),
        ),
    ]
