# Generated by Django 4.2.6 on 2024-06-26 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0030_includedchainid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allowlist",
            name="customization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allow_lists",
                to="account.customization",
            ),
        ),
    ]
