# Generated by Django 4.2.6 on 2024-07-08 22:07

from django.db import migrations, models

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0032_customization_body_display_info_tooltip_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountapikey",
            name="analysis_rate_limit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("15/15m", account.models.AnalysisRateLimits["TIER_1"]),
                    ("350/15m", account.models.AnalysisRateLimits["TIER_2"]),
                    ("2000/15m", account.models.AnalysisRateLimits["TIER_3"]),
                    ("", account.models.AnalysisRateLimits["UNLIMITED"]),
                ],
                default="15/15m",
                max_length=20,
                null=True,
            ),
        ),
    ]
