# Generated by Django 4.2.6 on 2024-09-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0035_customcredential_customcredentialruleset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customization",
            name="show_explanation_panel",
            field=models.BooleanField(
                default=True, help_text="Toggle to show or hide the middle component"
            ),
        ),
    ]
