# Generated by Django 4.2.6 on 2024-10-24 22:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0038_accountapikey_historical_endpoint"),
        ("account", "0038_accountapikeyanalytics_status_code"),
    ]

    operations = []
