# Generated by Django 4.2.6 on 2025-05-07 13:51

from django.db import migrations, models

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0039_merge_20241024_2219"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountapikey",
            name="embed_rate_limit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0/15m", account.models.EmbedRateLimits["TIER_1"]),
                    ("350/15m", account.models.EmbedRateLimits["TIER_2"]),
                    ("2000/15m", account.models.EmbedRateLimits["TIER_3"]),
                    ("", account.models.EmbedRateLimits["UNLIMITED"]),
                ],
                default="0/15m",
                max_length=20,
                null=True,
            ),
        ),
    ]
