# Generated by Django 4.2.6 on 2025-05-19 12:18

from django.db import migrations, models

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0040_accountapikey_embed_rate_limit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountapikey",
            name="embed_rate_limit",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0/15m", account.models.EmbedRateLimits["TIER_1"]),
                    ("1000/15m", account.models.EmbedRateLimits["TIER_2"]),
                    ("3000/15m", account.models.EmbedRateLimits["TIER_3"]),
                    ("", account.models.EmbedRateLimits["UNLIMITED"]),
                ],
                default="0/15m",
                max_length=20,
                null=True,
            ),
        ),
    ]
