# Generated by Django 4.2.6 on 2025-06-19 12:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0041_alter_accountapikey_embed_rate_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="customization",
            name="custom_dashboard_panel_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
