# Generated by Django 4.2.6 on 2025-06-20 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0042_customization_custom_dashboard_panel_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="human_points_program",
            field=models.BooleanField(
                default=False,
                help_text="Include this community in the Human Points Program stats.",
            ),
        ),
    ]
