# Generated by Django 4.2.6 on 2025-10-16 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0043_community_human_points_program"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountapikey",
            name="hashed_key_sha256",
            field=models.CharField(
                blank=True,
                help_text="SHA-256 hash for fast API key verification",
                max_length=71,
                null=True,
            ),
        ),
    ]
