# Generated by Django 4.2.6 on 2025-10-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0045_update_embed_rate_limit_values"),
    ]

    operations = [
        migrations.AddField(
            model_name="customization",
            name="nav_order",
            field=models.IntegerField(
                default=0,
                help_text="Order in which this dashboard appears in TopNav (lower numbers appear first)",
            ),
        ),
        migrations.AddField(
            model_name="customization",
            name="show_in_top_nav",
            field=models.BooleanField(
                default=False,
                help_text="Whether this dashboard should appear in the TopNav component",
            ),
        ),
    ]
