# Generated by Django 4.2 on 2025-01-16
# Migration for FeaturedCampaign model

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0047_populate_topnav_dashboards"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("partner_name", models.CharField(max_length=100)),
                (
                    "partner_logo",
                    models.TextField(blank=True, help_text="SVG string"),
                ),
                (
                    "image_tag",
                    models.CharField(
                        max_length=100,
                        help_text="Resolves to /assets/campaigns/{image_tag}.webp",
                    ),
                ),
                ("header_text", models.CharField(max_length=255)),
                ("body_text", models.TextField()),
                ("destination_url", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
    ]
