# Generated by Django 4.2.6 on 2026-01-26 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0048_add_embed_stamp_section_models"),
        ("account", "0049_populate_featured_campaigns"),
    ]

    operations = []
