# Generated by Django 4.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0052_flatten_embed_stamp_sections"),
    ]

    operations = [
        migrations.AddField(
            model_name="customplatform",
            name="is_evm",
            field=models.BooleanField(
                default=False,
                help_text="Whether this platform supports EVM on-chain verification",
            ),
        ),
        migrations.AlterField(
            model_name="customplatform",
            name="platform_type",
            field=models.CharField(
                choices=[("DEVEL", "Developer List"), ("NFT", "NFT Holder")],
                max_length=5,
            ),
        ),
        migrations.AlterField(
            model_name="customcredentialruleset",
            name="credential_type",
            field=models.CharField(
                choices=[("DEVEL", "Developer List"), ("NFT", "NFT Holder")],
                max_length=5,
            ),
        ),
    ]
