# Generated by Django 4.2.6 on 2026-09-21 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0055_walletgroup_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="organization_name",
            field=models.CharField(
                blank=True,
                help_text="The organization that owns this account. Required before a scorer is created in the Developer Portal",
                max_length=100,
                null=True,
            ),
        ),
    ]
