# Generated by Django 4.1.5 on 2023-01-27 18:09

from django.db import migrations, models

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0002_rename_passport_ceramiccache_stamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="ceramiccache",
            name="mark_as_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="ceramiccache",
            name="address",
            field=account.models.EthAddressField(
                db_index=True, max_length=100, null=True
            ),
        ),
    ]
