# Generated by Django 4.1.5 on 2023-01-27 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ceramic_cache", "0003_ceramiccache_mark_as_deleted_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ceramiccache",
            old_name="mark_as_deleted",
            new_name="deleted_at",
        ),
    ]
