# Generated by Django 4.1.5 on 2023-01-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceramic_cache", "0004_rename_mark_as_deleted_ceramiccache_deleted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ceramiccache",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
