# Generated by Django 4.1.5 on 2023-01-31 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ceramic_cache", "0004_rename_mark_as_deleted_ceramiccache_deleted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ceramiccache",
            name="deleted_at",
        ),
    ]
