# Generated by Django 4.1.5 on 2023-01-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0005_remove_ceramiccache_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="ceramiccache",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
