# Generated by Django 4.1.6 on 2023-02-08 20:13

from django.db import migrations


def remove_deleted_stamps(apps, schema_editor):
    CeramicCache = apps.get_model("ceramic_cache", "CeramicCache")
    CeramicCache.objects.filter(deleted_at__isnull=False).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0006_ceramiccache_deleted_at"),
    ]

    operations = [migrations.RunPython(remove_deleted_stamps)]
