# Generated by Django 4.1.6 on 2023-02-08 19:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0006_ceramiccache_deleted_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ceramiccache",
            name="deleted_at",
        ),
    ]
