# Generated by Django 4.1.6 on 2023-02-08 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0007_auto_20230208_2013"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ceramiccache",
            name="deleted_at",
        ),
    ]
