# Generated by Django 4.2.3 on 2023-07-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0008_remove_ceramiccache_deleted_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="StampExports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_export_ts", models.DateTimeField(auto_now_add=True)),
                ("stamp_total", models.IntegerField(default=0)),
            ],
        ),
    ]
