# Generated by Django 4.2.3 on 2023-07-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0009_stampexports"),
    ]

    operations = [
        migrations.AddField(
            model_name="ceramiccache",
            name="created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
