# Generated by Django 4.2.3 on 2023-07-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0010_ceramiccache_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ceramiccache",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
