# Generated by Django 4.2.3 on 2023-08-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0012_alter_ceramiccache_created_at_ceramiccachelegacy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ceramiccachelegacy",
            name="stamp",
            field=models.JSONField(db_index=True, default=dict),
        ),
    ]
