# Generated by Django 4.2.3 on 2023-08-21 21:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0013_alter_ceramiccachelegacy_stamp"),
    ]

    operations = [
        migrations.AddField(
            model_name="ceramiccache",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                default="1970-01-01T00:00:00Z",
                help_text="This is the timestamp that this DB record was updated (it is not necessarily the stamp issuance timestamp)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ceramiccache",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="This is the timestamp that this DB record was created (it is not necessarily the stamp issuance timestamp)",
                null=True,
            ),
        ),
        migrations.RunSQL(
            "UPDATE ceramic_cache_ceramiccache SET updated_at = created_at where created_at is not null",
            reverse_sql="",
        ),
    ]
