# Generated by Django 4.2.4 on 2023-09-06 08:04

from django.db import migrations, models

import ceramic_cache.models


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0014_ceramiccache_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ceramiccache",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="ceramiccache",
            name="type",
            field=models.IntegerField(
                choices=[(1, "V1"), (2, "V2")],
                default=ceramic_cache.models.CeramicCache.StampType["V1"],
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ceramiccache",
            unique_together={("type", "address", "provider")},
        ),
    ]
