# Generated by Django 4.2.6 on 2024-01-19 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ceramic_cache",
            "0015_alter_ceramiccache_unique_together_ceramiccache_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ceramiccache",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="ceramiccache",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="This is the timestamp that this DB record was deleted",
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ceramiccache",
            unique_together={("type", "address", "provider", "deleted_at")},
        ),
    ]
