# Generated by Django 4.2.6 on 2024-01-29 23:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0017_ceramiccache_compose_db_save_status_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                """delete from ceramic_cache_ceramiccache as older where exists
                (select 1 from ceramic_cache_ceramiccache as newer where newer.address = older.address and
                newer.provider = older.provider and newer.deleted_at is null and older.deleted_at is null and
                newer.type = older.type and newer.created_at > older.created_at);"""
            ),
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
