# Generated by Django 4.2.6 on 2024-02-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0017_ceramiccache_compose_db_save_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ceramiccache",
            name="provider_clone",
            field=models.CharField(
                blank=True, db_index=True, default=None, max_length=256, null=True
            ),
        ),
        migrations.AlterField(
            model_name="ceramiccache",
            name="compose_db_stream_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Compose db stream ID for CREDENTIAL WRAPPER",
                max_length=100,
            ),
        ),
        migrations.AddConstraint(
            model_name="ceramiccache",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("type", "address", "provider_clone"),
                name="unique_non_deleted_provider_clone_per_address",
            ),
        ),
        migrations.AddConstraint(
            model_name="ceramiccache",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", False)),
                fields=("type", "address", "provider_clone", "deleted_at"),
                name="unique_deleted_provider_clone_per_address",
            ),
        ),
    ]
