# Generated by Django 4.2.6 on 2024-02-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0017_ceramiccache_compose_db_save_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ceramiccache",
            name="compose_db_stream_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Compose db stream ID for CREDENTIAL WRAPPER",
                max_length=100,
            ),
        ),
    ]
