# Generated by Django 4.2.6 on 2024-02-07 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0018_ceramiccache_provider_clone_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ceramiccache",
            name="unique_non_deleted_provider_clone_per_address",
        ),
        migrations.RemoveConstraint(
            model_name="ceramiccache",
            name="unique_deleted_provider_clone_per_address",
        ),
        migrations.RemoveField(
            model_name="ceramiccache",
            name="provider_clone",
        ),
        migrations.AddConstraint(
            model_name="ceramiccache",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("type", "address", "provider"),
                name="unique_non_deleted_provider_for_address",
            ),
        ),
        migrations.AddConstraint(
            model_name="ceramiccache",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", False)),
                fields=("type", "address", "provider", "deleted_at"),
                name="unique_deleted_provider_for_address",
            ),
        ),
    ]
