# Generated by Django 4.2.6 on 2024-01-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0018_remove_dups"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ceramiccache",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="ceramiccache",
            name="compose_db_stream_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Compose db stream ID for CREDENTIAL WRAPPER",
                max_length=100,
            ),
        ),
        migrations.AddConstraint(
            model_name="ceramiccache",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("type", "address", "provider"),
                name="unique_non_deleted_provider_per_address",
            ),
        ),
        migrations.AddConstraint(
            model_name="ceramiccache",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", False)),
                fields=("type", "address", "provider", "deleted_at"),
                name="unique_deleted_provider_per_address",
            ),
        ),
    ]
