# Generated by Django 4.2.6 on 2024-02-13 10:32

from django.db import migrations, models

import ceramic_cache.models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ceramic_cache",
            "0019_remove_ceramiccache_unique_non_deleted_provider_clone_per_address_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ceramiccache",
            name="compose_db_save_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending"),
                    ("saved", "Saved"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="ceramiccache",
            name="compose_db_stream_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Compose db stream ID for CREDENTIAL WRAPPER",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ceramiccache",
            name="type",
            field=models.IntegerField(
                choices=[(1, "V1"), (2, "V2")],
                default=ceramic_cache.models.CeramicCache.StampType["V1"],
                help_text="TO BE DELETED - this is not used",
            ),
        ),
    ]
