# Generated by Django 4.2.6 on 2024-06-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ceramic_cache", "0021_ceramiccache_expiration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ceramiccache",
            name="expiration_date",
            field=models.DateTimeField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="ceramiccache",
            name="issuance_date",
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
