# Generated by Django 4.2.6 on 2024-08-01 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0021_ceramiccache_expiration_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ceramiccache",
            name="proof_value",
            field=models.CharField(db_index=True, default="", max_length=256),
        ),
        migrations.CreateModel(
            name="Revocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "proof_value",
                    models.CharField(db_index=True, max_length=256, unique=True),
                ),
                (
                    "ceramic_cache",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revocation",
                        to="ceramic_cache.ceramiccache",
                    ),
                ),
            ],
        ),
    ]
