# Generated by Django 4.2.6 on 2024-08-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0023_alter_ceramiccache_proof_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="revocation",
            name="proof_value",
            field=models.CharField(db_index=True, max_length=256),
        ),
    ]
