# Generated by Django 4.2.6 on 2024-11-28 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0025_ban"),
    ]

    operations = [
        migrations.CreateModel(
            name="BanList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("csv_file", models.FileField(max_length=1024, upload_to="")),
                (
                    "name",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=256, null=True
                    ),
                ),
                ("description", models.TextField(blank=True, default="", null=True)),
            ],
        ),
        migrations.AddField(
            model_name="ban",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("account", "Account"),
                    ("hash", "Hash"),
                    ("single_stamp", "SingleStamps"),
                ],
                default=None,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ban",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="ban",
            name="end_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="ban",
            name="ban_list",
            field=models.ForeignKey(
                blank=True,
                default=None,
                help_text="If set, this ban was created as part of a larger ban list",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="ceramic_cache.banlist",
            ),
        ),
    ]
