# Generated by Django 4.2.6 on 2024-12-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0027_revocationlist_alter_banlist_csv_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banlist",
            name="csv_file",
            field=models.FileField(
                help_text="CSV file for stamps to revoke. The CSV need sto have at least the following columns \n        `type`, `provider`, `hash`, `address`, `end_time` (if empty of `null` will be considered null) to \n        identify the ban. If a value is not relevant for a prticular ban, it can be left empty.\n        Other columns are ignored.",
                max_length=1024,
                upload_to="ban_list",
            ),
        ),
        migrations.AlterField(
            model_name="revocationlist",
            name="csv_file",
            field=models.FileField(
                help_text="CSV file for stamps to revoke. The CSV need sto have at least one column named \n        `proof_value` to identify which stamp to revoke. Other columns are ignored.",
                max_length=1024,
                upload_to="revocation_list",
            ),
        ),
    ]
