# Generated by Django 4.2.6 on 2024-12-03 14:08

from django.db import migrations, models

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ("ceramic_cache", "0028_alter_banlist_csv_file_alter_revocationlist_csv_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ban",
            name="address",
            field=account.models.EthAddressField(
                blank=True,
                db_index=True,
                default="",
                help_text="Address to ban",
                max_length=42,
            ),
        ),
        migrations.AlterField(
            model_name="ban",
            name="end_time",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="Leave blank for indefinite ban",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ban",
            name="hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Specific credential hash to ban",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="ban",
            name="provider",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Provider (e.g. CoinbaseDualVerification) to ban - must be used with address",
                max_length=256,
            ),
        ),
        migrations.AlterField(
            model_name="ban",
            name="reason",
            field=models.TextField(
                blank=True,
                help_text="(Optional) THIS WILL BE PUBLICLY VISIBLE",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="banlist",
            name="csv_file",
            field=models.FileField(
                help_text="CSV file for stamps to revoke. The CSV need sto have at least the following columns\n        `type`, `provider`, `hash`, `address`, `end_time` (if empty of `null` will be considered null) to\n        identify the ban. If a value is not relevant for a prticular ban, it can be left empty.\n        Other columns are ignored.",
                max_length=1024,
                upload_to="ban_list",
            ),
        ),
        migrations.AlterField(
            model_name="revocationlist",
            name="csv_file",
            field=models.FileField(
                help_text="CSV file for stamps to revoke. The CSV need sto have at least one column named\n        `proof_value` to identify which stamp to revoke. Other columns are ignored.",
                max_length=1024,
                upload_to="revocation_list",
            ),
        ),
    ]
