# Generated by Django 4.2.6 on 2024-12-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ceramic_cache",
            "0029_alter_ban_address_alter_ban_end_time_alter_ban_hash_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ceramiccache",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text="This is the timestamp that this DB record was created (it is not necessarily the stamp issuance timestamp)",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ceramiccache",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                db_index=True,
                help_text="This is the timestamp that this DB record was deleted",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="ceramiccache",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                db_index=True,
                help_text="This is the timestamp that this DB record was updated (it is not necessarily the stamp issuance timestamp)",
            ),
        ),
    ]
