# Generated by Django 4.2.6 on 2025-01-10 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ceramic_cache",
            "0029_alter_ban_address_alter_ban_end_time_alter_ban_hash_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="ceramiccache",
            name="scorer_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="This is field is only used to indicate for analytic purposes which scorer was targeted \n        when claiming the users credential (when used from embed, it will indicate what scorer id was set in \n        the embed component)",
                null=True,
                verbose_name="Scorer ID",
            ),
        ),
        migrations.AddField(
            model_name="ceramiccache",
            name="stamp_created_by",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Passport"), (2, "Embed")],
                db_index=True,
                help_text="Which entity created the stamp. At the moment there are 2 options: the 'Passport App' and 'Embed Widget'",
                null=True,
                verbose_name="Creating Enity",
            ),
        ),
    ]
