# Generated by Django 4.1.1 on 2022-10-03 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registry", "0001_initial"),
        ("scorer_apu", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="score",
            name="passport",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="apu_scores",
                to="registry.passport",
            ),
        ),
    ]
