# Generated by Django 4.2.2 on 2023-07-13 22:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cgrants", "0002_subscription_is_mainnet"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="success",
            field=models.BooleanField(default=False),
        ),
    ]
