# Generated by Django 4.2.2 on 2023-07-14 16:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cgrants", "0003_contribution_success"),
    ]

    operations = [
        migrations.AddField(
            model_name="contribution",
            name="amount_per_period_usdt",
            field=models.DecimalField(
                decimal_places=18,
                default=0,
                help_text="The amount per contribution period in USDT",
                max_digits=64,
            ),
        ),
    ]
