# Generated by Django 4.2.3 on 2023-07-20 14:29

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cgrants", "0004_contribution_amount_per_period_usdt"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProtocolContributions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contributor",
                    account.models.EthAddressField(
                        db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "round",
                    account.models.EthAddressField(
                        db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "project",
                    account.models.EthAddressField(
                        db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "amount_usd",
                    models.DecimalField(
                        db_index=True,
                        decimal_places=18,
                        default=0,
                        help_text="The USD amount contributed",
                        max_digits=64,
                    ),
                ),
            ],
        ),
    ]
