# Generated by Django 4.2.3 on 2023-08-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cgrants", "0005_protocolcontributions_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="github_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="This is the github users unique id. This should not change even if the user changes his handle. The handle might be duplicate (this can happen if the user changed his handle ...)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="notes",
            field=models.TextField(
                blank=True,
                help_text="These notes are intended for the support team, in case they make manual adjustments to the profile.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="handle",
            field=models.CharField(
                db_index=True,
                help_text="DEPRECATED: The github handle of the user. This has been deprecated in favour of github_id.",
                max_length=255,
                unique=True,
            ),
        ),
    ]
