# Generated by Django 4.2.3 on 2023-08-04 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cgrants", "0006_profile_github_id_profile_notes_alter_profile_handle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="github_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="This is the github users unique id. This should not change even if the user changes his handle.",
                null=True,
                unique=True,
            ),
        ),
    ]
