# Generated by Django 4.2.6 on 2023-10-26 16:23

from django.db import migrations

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ("cgrants", "0006_profile_github_id_profile_notes_alter_profile_handle"),
    ]

    operations = [
        migrations.AddField(
            model_name="grantcontributionindex",
            name="contributor_address",
            field=account.models.EthAddressField(blank=True, max_length=100, null=True),
        ),
    ]
