# Generated by Django 4.2.6 on 2023-12-18 22:49

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cgrants", "0007_grantcontributionindex_contributor_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="SquelchedAccounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    account.models.EthAddressField(
                        blank=True, db_index=True, max_length=100, null=True
                    ),
                ),
                (
                    "score_when_squelched",
                    models.DecimalField(decimal_places=18, default=0, max_digits=64),
                ),
                ("sybil_signal", models.BooleanField(default=False)),
            ],
        ),
    ]
