# Generated by Django 4.2.6 on 2024-01-09 18:38

from django.db import migrations, models

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ("cgrants", "0008_squelchedaccounts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="squelchedaccounts",
            options={"verbose_name_plural": "Squelched Accounts - GG Rounds 18 +"},
        ),
        migrations.AddField(
            model_name="squelchedaccounts",
            name="round_number",
            field=models.IntegerField(
                default=0, help_text="GG Round number when account was squelched"
            ),
        ),
        migrations.CreateModel(
            name="RoundMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "round_number",
                    models.DecimalField(
                        db_index=True, decimal_places=18, max_digits=64
                    ),
                ),
                (
                    "round_eth_address",
                    account.models.EthAddressField(db_index=True, max_length=100),
                ),
            ],
            options={
                "unique_together": {("round_number", "round_eth_address")},
            },
        ),
    ]
