# Generated by Django 4.2.6 on 2024-01-09 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cgrants", "0009_alter_squelchedaccounts_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roundmapping",
            name="round_number",
            field=models.IntegerField(
                default=0, help_text="GG Round number associated with round address"
            ),
        ),
    ]
