# Generated by Django 4.2.6 on 2024-12-19 15:02

from django.db import migrations

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ("cgrants", "0011_alter_roundmapping_round_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grantcontributionindex",
            name="contributor_address",
            field=account.models.EthAddressField(
                blank=True, db_index=True, max_length=100, null=True
            ),
        ),
    ]
