# Generated by Django 4.1.4 on 2022-12-09 09:45

from django.db import migrations, models
import django.db.models.deletion
import scorer_weighted.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Scorer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("WEIGHTED", "Weighted"),
                            ("WEIGHTED_BINARY", "Weighted Binary"),
                        ],
                        default="WEIGHTED",
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BinaryWeightedScorer",
            fields=[
                (
                    "scorer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="scorer_weighted.scorer",
                    ),
                ),
                (
                    "weights",
                    models.JSONField(
                        blank=True,
                        default=scorer_weighted.models.get_default_weights,
                        null=True,
                    ),
                ),
                ("threshold", models.DecimalField(decimal_places=5, max_digits=10)),
            ],
            bases=("scorer_weighted.scorer",),
        ),
        migrations.CreateModel(
            name="WeightedScorer",
            fields=[
                (
                    "scorer_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="scorer_weighted.scorer",
                    ),
                ),
                (
                    "weights",
                    models.JSONField(
                        blank=True,
                        default=scorer_weighted.models.get_default_weights,
                        null=True,
                    ),
                ),
            ],
            bases=("scorer_weighted.scorer",),
        ),
    ]
