# Generated by Django 4.1.4 on 2023-01-09 16:55

from django.db import migrations, models

import scorer_weighted.models


class Migration(migrations.Migration):
    dependencies = [
        ("scorer_weighted", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="binaryweightedscorer",
            name="threshold",
            field=models.DecimalField(
                decimal_places=5,
                default=scorer_weighted.models.get_default_threshold,
                max_digits=10,
            ),
        ),
    ]
