# Generated by Django 4.2.6 on 2025-05-09 19:56

from django.db import migrations, models

import scorer_weighted.models


class Migration(migrations.Migration):
    dependencies = [
        ("scorer_weighted", "0004_rescorerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="weightedscorer",
            name="threshold",
            field=models.DecimalField(
                decimal_places=5,
                default=scorer_weighted.models.get_default_threshold,
                max_digits=10,
            ),
        ),
    ]
