name: Deploy UI to Staging

on:
  workflow_dispatch:
    inputs:
      commit:
        description: "Leave blank to use current HEAD, or provide an override commit SHA"
        type: string
        required: false
jobs:
  ui-test:
    # TODO (#106): Remove this job once the interface is fully migrated to S3, ui tests are also run as part of the build

    runs-on: ubuntu-latest

    steps:
      - id: ref
        uses: passportxyz/gh-workflows/.github/actions/load_commit_ref@v1
        with:
          commit: ${{ github.event.inputs.commit }}

      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.ref.outputs.refspec }}
          fetch-depth: 0

      - name: Install UI dependencies
        working-directory: ./interface
        run: yarn --frozen-lockfile && yarn build

      - name: Run tests
        working-directory: ./interface
        run: yarn test

    outputs:
      version_tag: ${{ steps.ref.outputs.version_tag }}
      docker_tag: ${{ steps.ref.outputs.docker_tag }}
      refspec: ${{ steps.ref.outputs.refspec }}

  deploy-app:
    # TODO (#106): remove this after deploy to S3 is final
    needs: [ui-test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ needs.ui-test.outputs.refspec }}
          fetch-depth: 0
      - name: Push code to branch
        uses: passportxyz/gh-workflows/.github/actions/push_to_branch@v1
        with:
          commit: ${{ needs.ui-test.outputs.refspec }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          branch: staging-interface

  build-app:
    name: Build App
    uses: ./.github/workflows/sync_to_s3_generic_build_app.yml
    secrets: inherit
    with:
      refspec: ${{ needs.ui-test.outputs.refspec }}
      environment: staging

  push-app-to-s3:
    name: Push App
    needs: [build-app]
    uses: ./.github/workflows/sync_to_s3_generic_push_app.yml
    secrets: inherit
    with:
      refspec: ${{ needs.ui-test.outputs.refspec }}
      environment: staging
