# Generated by Django 4.2.3 on 2023-08-03 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("passport_admin", "0001_initial"),
        ("passport_admin", "0002_rename_description_passportbanner_content_and_more"),
        ("passport_admin", "0003_remove_passportbanner_name"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PassportBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("link", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="DismissedBanners",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                (
                    "banner",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dismissedbanners",
                        to="passport_admin.passportbanner",
                    ),
                ),
            ],
        ),
    ]
