# Generated by Django 4.2.3 on 2023-08-02 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("passport_admin", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="passportbanner",
            old_name="description",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="passportbanner",
            old_name="title",
            new_name="name",
        ),
    ]
