# Generated by Django 4.2.3 on 2023-08-03 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("passport_admin", "0002_rename_description_passportbanner_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="passportbanner",
            name="name",
        ),
    ]
