# Generated by Django 4.2.6 on 2024-06-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("passport_admin", "0004_passportbanner_application"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notification_id", models.CharField(max_length=100, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("custom", "Custom"),
                            ("expiry", "Expiry"),
                            ("deduplication", "Deduplication"),
                        ],
                        db_index=True,
                        default="custom",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("created_at", models.DateField(auto_now_add=True)),
                ("expires_at", models.DateField()),
                ("eth_address", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DismissedNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dismissed", models.BooleanField()),
                ("eth_address", models.CharField(max_length=255)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="passport_admin.notification",
                    ),
                ),
            ],
        ),
    ]
