# Generated by Django 4.2.6 on 2024-06-17 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passport_admin", "0004_passportbanner_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="passportbanner",
            name="application",
            field=models.CharField(
                choices=[("passport", "Passport"), ("id_staking_v2", "ID Staking V2")],
                db_index=True,
                default="passport",
                max_length=50,
            ),
        ),
    ]
