# Generated by Django 4.2.6 on 2024-07-03 16:16

import account.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("passport_admin", "0005_alter_passportbanner_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dismissedbanners",
            name="address",
            field=account.models.EthAddressField(max_length=42),
        ),
    ]
