# Generated by Django 4.2.6 on 2024-06-20 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("passport_admin", "0005_notification_dismissednotification"),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("eth_address", models.CharField(max_length=255)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="passport_admin.notification",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="DismissedNotification",
        ),
    ]
