# Generated by Django 4.2.6 on 2024-07-12 15:55

import django.db.models.deletion
from django.db import migrations, models

import passport_admin.models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0032_customization_body_display_info_tooltip_and_more"),
        ("passport_admin", "0006_notification_alter_dismissedbanners_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="community",
            field=models.ForeignKey(
                default=passport_admin.models.get_default_ceramic_cache_community,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notifications",
                to="account.community",
            ),
        ),
    ]
