# Generated by Django 4.2.6 on 2024-08-01 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passport_admin", "0007_notification_community"),
    ]

    operations = [
        migrations.CreateModel(
            name="LastScheduledRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255, unique=True)),
                ("last_run", models.DateTimeField()),
            ],
        ),
    ]
