# Generated by Django 4.2.6 on 2024-06-20 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passport_admin", "0007_remove_notification_title_notification_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
