# Generated by Django 4.2.6 on 2024-06-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passport_admin", "0008_alter_notification_notification_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="expires_at",
            field=models.DateField(null=True),
        ),
    ]
