# Generated by Django 4.2.6 on 2024-11-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passport_admin", "0008_lastscheduledrun"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notificationstatus",
            name="is_deleted",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="notificationstatus",
            name="is_read",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
