# Generated by Django 4.2.6 on 2024-11-08 09:02

from django.db import migrations, models

import account.models


class Migration(migrations.Migration):
    dependencies = [
        ("passport_admin", "0009_alter_notificationstatus_is_deleted_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="eth_address",
            field=account.models.EthAddressField(
                blank=True, db_index=True, max_length=42, null=True
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="expires_at",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_active",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
