# Generated by Django 4.2.6 on 2024-12-12 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passport_admin", "0010_alter_notification_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemTestRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SystemTestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("category", models.JSONField(default=list)),
                ("success", models.BooleanField(default=False)),
                ("error", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(db_index=True)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="results",
                        to="passport_admin.systemtestrun",
                    ),
                ),
            ],
        ),
    ]
