# Generated by Django 4.2.6 on 2025-03-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passport_admin", "0011_systemtestrun_systemtestresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemtestrun",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
