# Generated by Django 4.2.6 on 2025-04-18 14:04
from django.db import migrations, models


def set_finished_to_true(apps, schema_editor):
    SystemTestRun = apps.get_model("passport_admin", "SystemTestRun")
    SystemTestRun.objects.all().update(finished=True)


class Migration(migrations.Migration):
    dependencies = [
        ("passport_admin", "0012_systemtestrun_timestamp"),
    ]
    operations = [
        migrations.AddField(
            model_name="systemtestrun",
            name="finished",
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_finished_to_true),
    ]
