# Generated by Django 4.2.6 on 2025-04-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passport_admin", "0013_systemtestrun_finished"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="is_outdated",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indicates that the underlying condition for which the notification was created no lobger exists.For example, a user has reclaimed an expired stamp.",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="This flag will typically be used for `custom` attestations, not bound to a specific address.",
            ),
        ),
    ]
