# Generated by Django 4.2.6 on 2025-05-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("passport_admin", "0013_systemtestrun_finished"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="is_active",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="This flag will typically be used for `custom` attestations, not bound to a specific address.",
            ),
        ),
    ]
