# Generated by Django 4.2.6 on 2025-08-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("passport_admin", "0014_alter_notification_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="passportbanner",
            name="display_on_all_dashboards",
            field=models.BooleanField(
                default=True,
                help_text="When checked, this banner will be displayed on all Passport App dashboards (including custom dashboards). When unchecked, this banner will only be displayed on the standard Passport App dashboard and will not appear in custom dashboards.",
            ),
        ),
    ]
